[package]
name = "vanadium"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
sync = { path = "../shared/sync" }

[features]
"platform.virt" = []
"platform.sifive_u" = []
